<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Smoke_Datafiles</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>cbabee21-8c2e-484e-9352-a22da242767b</testSuiteGuid>
   <testCaseLink>
      <guid>701eb25c-e6bd-45b7-a70b-09bdaf247d7a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Form/Test_FillUpForm with DataFiles</testCaseId>
      <testDataLink>
         <combinationType>MANY</combinationType>
         <id>b38bb553-d065-4e5d-97cd-7aa9c8bb5beb</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/users</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a1545c1-fb13-4201-917a-47704f46fb71</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b38bb553-d065-4e5d-97cd-7aa9c8bb5beb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>first_name</value>
         <variableId>d846a0d3-1354-43a1-948e-9504e0029cb6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b38bb553-d065-4e5d-97cd-7aa9c8bb5beb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>last_name</value>
         <variableId>2cc10999-e039-4adf-b22d-93e76fdce2ee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b38bb553-d065-4e5d-97cd-7aa9c8bb5beb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>date</value>
         <variableId>ae357cc1-87b9-477d-a630-2f62453789fc</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
