<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Ad_ad_iframe</name>
   <tag></tag>
   <elementGuidId>37da9c4f-d575-4a1b-8def-7fd4211ed888</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ad_iframe']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ad_iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>67526a19-f493-4336-8208-b5821cabc33b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Advertisement</value>
      <webElementGuid>65d856f0-db22-4f16-bcc7-62d980712612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ad_iframe</value>
      <webElementGuid>e550dc96-33e0-471e-89ef-5e505d3101e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ad_iframe</value>
      <webElementGuid>d2d5fc40-3f80-4cfc-b57f-70a5f4ee2853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>c0eb2224-df14-48a0-9b4c-d3de38528965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>about:blank</value>
      <webElementGuid>696a4545-bb0f-49d9-8927-e146a39e45df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8dbe01e7-5918-4aac-b1a1-5d292e0bbf48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>365px</value>
      <webElementGuid>b1166371-4e2e-43b1-83ef-bab550e4620a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>394px</value>
      <webElementGuid>a4d4324e-ed9e-46b6-aa07-bf499601d4dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ad_iframe&quot;)</value>
      <webElementGuid>c7d82034-b207-4dfd-ae08-b27e2077f248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_FillUpForm/iframe_concat(id(, , google_ads_iframe_1254_2fb17c</value>
      <webElementGuid>c1459142-70f9-4a64-beca-495505d984c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ad_iframe']</value>
      <webElementGuid>578b6035-0299-4dfb-895c-bf2ab2afb331</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='creative']/iframe</value>
      <webElementGuid>133aae1c-3a75-4c50-92fa-4bbb157c8afd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>5a639edb-a82e-42c0-a5c8-9cc9d5f108f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'Advertisement' and @id = 'ad_iframe' and @name = 'ad_iframe' and @src = 'about:blank']</value>
      <webElementGuid>871d049a-3fd9-4eb0-90a4-363c30a3f065</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
