<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Years of Experience_exp</name>
   <tag></tag>
   <elementGuidId>9038a563-eb74-45e3-90ec-dbf20a209f36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='exp-5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#exp-5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4ba0ae15-e223-4c8e-96b8-53a9fe64d0ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>exp-5</value>
      <webElementGuid>753c6718-f69a-44e9-aca1-e21e7c321888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exp</value>
      <webElementGuid>b56fc53d-24ce-4689-9b3c-36c228eed4a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>2b33628b-d326-400c-a1f4-b469b2474349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>a250047d-e445-4204-a08c-bb37d98a3d2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;exp-5&quot;)</value>
      <webElementGuid>4d3356f6-9492-4ec6-8b9b-e2d028af5769</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='exp-5']</value>
      <webElementGuid>b497f616-86ee-4525-83d1-4c0f1c83e6bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='post-body-3077692503353518311']/div/div/div/h2[2]/div/div/div[14]/input[6]</value>
      <webElementGuid>6720e546-2eb6-4cd3-bc74-029a9305af02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[6]</value>
      <webElementGuid>05aa25c0-6ee9-4037-9d1e-78291362619e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'exp-5' and @name = 'exp' and @type = 'radio']</value>
      <webElementGuid>fcb9311f-54e8-460b-b6af-15e2ef6ee585</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
