<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Gender_sex</name>
   <tag></tag>
   <elementGuidId>ac4da89c-fd1f-43d9-807f-98f86f4d6134</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sex-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sex-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>74cfab5c-41e1-4d18-af62-559757594d57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sex-0</value>
      <webElementGuid>5a12ac42-ab4c-47ba-b6ec-0a2862ae0152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sex</value>
      <webElementGuid>63967d95-0ae0-497a-a743-fd8e6f8a3c65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>b662cd12-0793-4593-b37c-8fcb4b2029d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Male</value>
      <webElementGuid>2a6b4960-2aaa-4881-93b9-51a73856a2cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sex-0&quot;)</value>
      <webElementGuid>bdc48cf0-f1dd-4d61-999f-91a44fb05c56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sex-0']</value>
      <webElementGuid>08dc66bc-bce5-4532-8195-6dc5d9a82921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='post-body-3077692503353518311']/div/div/div/h2[2]/div/div/div[9]/input</value>
      <webElementGuid>8010da8e-9574-4df5-aa68-5b1d07b9fb52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/input</value>
      <webElementGuid>4a7cad5e-83a5-4981-8949-fbf0203be1a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'sex-0' and @name = 'sex' and @type = 'radio']</value>
      <webElementGuid>377cb6eb-683c-4447-b9e3-468389459d6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
