<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_AsiaEuropeAfricaAustraliaSouth Ameri_982c86</name>
   <tag></tag>
   <elementGuidId>eae83cfc-b2b4-4918-90bf-ed14902d3c19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='continents']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#continents</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0e799f1e-04be-4998-916e-a9c61c1670e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-xlarge</value>
      <webElementGuid>81256158-ffab-4895-b544-f3831199c456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>continents</value>
      <webElementGuid>f363a07a-15cb-4849-b565-49654ef82407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>continents</value>
      <webElementGuid>724431be-fa37-4434-8c5c-3a7ac76ce900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AsiaEuropeAfricaAustraliaSouth AmericaNorth AmericaAntartica</value>
      <webElementGuid>ebf92ea1-212a-4215-9a65-540319b23853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;continents&quot;)</value>
      <webElementGuid>4bfbe7e1-1e23-46b0-b64a-92d7568b88a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='continents']</value>
      <webElementGuid>985ec80f-74cf-44d0-b39f-abb0daa28b84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='post-body-3077692503353518311']/div/div/div/h2[2]/div/div/div[25]/div[2]/select</value>
      <webElementGuid>52306e89-2bf7-4e13-882c-931b31db8306</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continents'])[1]/following::select[1]</value>
      <webElementGuid>a19c9534-5534-480c-a564-e2f3f6e52090</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation Tools'])[1]/following::select[1]</value>
      <webElementGuid>08538052-b57d-4b39-a8b6-531794b3d960</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selenium Commands'])[1]/preceding::select[1]</value>
      <webElementGuid>63fb0962-80df-4b2c-b50f-e1cfede248dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload Image'])[1]/preceding::select[2]</value>
      <webElementGuid>9f494c20-549b-4a0e-bbf0-0e58e36bb861</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>37324e26-d201-47b7-83af-54c24f6f9fde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'continents' and @name = 'continents' and (text() = 'AsiaEuropeAfricaAustraliaSouth AmericaNorth AmericaAntartica' or . = 'AsiaEuropeAfricaAustraliaSouth AmericaNorth AmericaAntartica')]</value>
      <webElementGuid>a5a6cd62-9979-44ff-b5c9-c940160306eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
